import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"


import { RowData } from "./Interfaces";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}






// Example of mock data for the table
export const mockData: RowData[] = [
  {
    id: "1",
    ref: "K7UGXO-7EPT06",
    pickupTime: "154, Block 5 Clifton, Karachi, Pakistan",
    dropOff: "ST-16 Main University Rd, Karachi, Pakistan",
    customer: "maaz",
    phone: "1239874521",
    vehicleType: 3,
    status: "Pending",
    driver: "",
    fare: 93.48,
    bookingDate: "2024-11-11",
  },
  {
    id: "2",
    ref: "L1QWEO-9JHGT12",
    pickupTime: "1st Floor, Sadar, Karachi, Pakistan",
    dropOff: "Bahria Town, Karachi, Pakistan",
    customer: "Zara",
    phone: "7896541230",
    vehicleType: 2,
    status: "Completed",
    driver: "Ali",
    fare: 50.75,
    bookingDate: "2024-11-15",
  },
  {
    id: "3",
    ref: "T4KZPX-8BNJY30",
    pickupTime: "Liberty Market, Lahore, Pakistan",
    dropOff: "DHA Phase 5, Lahore, Pakistan",
    customer: "Ahmed",
    phone: "3216549870",
    vehicleType: 1,
    status: "Cancelled",
    driver: "Sara",
    fare: 120.00,
    bookingDate: "2024-11-13",
  },
  {
    id: "4",
    ref: "N2MWXY-6CKOZ01",
    pickupTime: "Gulshan-e-Iqbal, Karachi, Pakistan",
    dropOff: "Korangi, Karachi, Pakistan",
    customer: "Hassan",
    phone: "4561237890",
    vehicleType: 3,
    status: "Pending",
    driver: "",
    fare: 85.60,
    bookingDate: "2024-11-16",
  },
  {
    id: "5",
    ref: "F3XYZO-1AOLP23",
    pickupTime: "Faisalabad, Pakistan",
    dropOff: "Lahore, Pakistan",
    customer: "Nadia",
    phone: "5478392014",
    vehicleType: 2,
    status: "Completed",
    driver: "Imran",
    fare: 150.20,
    bookingDate: "2024-11-14",
  },
  {
    id: "6",
    ref: "W8OQZR-5MNVK34",
    pickupTime: "Karachi Airport, Karachi, Pakistan",
    dropOff: "Karachi Saddar, Pakistan",
    customer: "Omar",
    phone: "9786543210",
    vehicleType: 1,
    status: "Completed",
    driver: "Usman",
    fare: 45.30,
    bookingDate: "2024-11-17",
  },
  {
    id: "7",
    ref: "R2JSIT-4GPLO45",
    pickupTime: "Karachi Port, Karachi, Pakistan",
    dropOff: "Malir, Karachi, Pakistan",
    customer: "Mariam",
    phone: "9102837465",
    vehicleType: 3,
    status: "Completed",
    driver: "Nashit",
    fare: 60.90,
    bookingDate: "2024-11-18",
  },
  {
    id: "8",
    ref: "B1RTUV-3AWXI67",
    pickupTime: "Khyber Market, Peshawar, Pakistan",
    dropOff: "University Town, Peshawar, Pakistan",
    customer: "Nashit",
    phone: "6574839201",
    vehicleType: 2,
    status: "Pending",
    driver: "",
    fare: 110.80,
    bookingDate: "2024-11-19",
  },
  {
    id: "9",
    ref: "J5VBYO-2UQEG56",
    pickupTime: "Mardan, Pakistan",
    dropOff: "Peshawar, Pakistan",
    customer: "Bilal",
    phone: "7382928471",
    vehicleType: 3,
    status: "Cancelled",
    driver: "Irfan",
    fare: 95.40,
    bookingDate: "2024-11-20",
  },
  {
    id: "10",
    ref: "H7VJLS-8CRAK91",
    pickupTime: "Faisalabad, Pakistan",
    dropOff: "Sargodha, Pakistan",
    customer: "Ali",
    phone: "2348671529",
    vehicleType: 1,
    status: "Pending",
    driver: "",
    fare: 80.15,
    bookingDate: "2024-11-21",
  },
  {
    id: "11",
    ref: "G4JKTU-9XNZO12",
    pickupTime: "Rawalpindi, Pakistan",
    dropOff: "Islamabad, Pakistan",
    customer: "Junaid",
    phone: "8937164520",
    vehicleType: 2,
    status: "Completed",
    driver: "Sahil",
    fare: 70.60,
    bookingDate: "2024-11-22",
  },
  {
    id: "12",
    ref: "K9PWIQ-6GZRI31",
    pickupTime: "Karachi Downtown, Pakistan",
    dropOff: "Karachi Korangi, Pakistan",
    customer: "Anwar",
    phone: "5647382910",
    vehicleType: 3,
    status: "Pending",
    driver: "",
    fare: 92.30,
    bookingDate: "2024-11-23",
  },
  {
    id: "13",
    ref: "M6PDUO-2IJNB58",
    pickupTime: "Sialkot, Pakistan",
    dropOff: "Gujranwala, Pakistan",
    customer: "Khalid",
    phone: "9816274350",
    vehicleType: 1,
    status: "Completed",
    driver: "Raza",
    fare: 120.00,
    bookingDate: "2024-11-24",
  },
  {
    id: "14",
    ref: "A8VXZO-4LQYT59",
    pickupTime: "Multan, Pakistan",
    dropOff: "Lahore, Pakistan",
    customer: "Faizan",
    phone: "6458391208",
    vehicleType: 2,
    status: "Cancelled",
    driver: "Javed",
    fare: 150.50,
    bookingDate: "2024-11-25",
  },
  {
    id: "15",
    ref: "P3KXZI-7LJYV60",
    pickupTime: "Bahawalpur, Pakistan",
    dropOff: "Karachi, Pakistan",
    customer: "Shahbaz",
    phone: "7458362109",
    vehicleType: 1,
    status: "Completed",
    driver: "Kashif",
    fare: 180.30,
    bookingDate: "2024-11-26",
  },
];